name 'nbb'
maintainer 'Kevin Pheasey'
maintainer_email 'kevin@kpsoftware.io'
license 'all_rights'
description 'Installs/Configures opsworks_ruby'
long_description 'Installs/Configures opsworks_ruby'
version '0.1.0'

depends 'opsworks_ruby'
depends 'opsworks_whenever'
depends 'swap'
