name 'nbb'
maintainer 'Kevin Pheasey'
maintainer_email 'kevin@kpheasey.com'
license 'all_rights'
description 'Installs/Configures opsworks_nbb'
long_description 'Installs/Configures opsworks_nbb'
version '0.1.0'

depends 'cloudwatch-logs'
depends 'opsworks_ruby'
depends 'opsworks_whenever'
depends 'swap'
